-- MySQL Script generated by MySQL Workbench
-- 03/03/16 10:55:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projectx
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projectx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectx` DEFAULT CHARACTER SET latin1 ;
USE `projectx` ;

-- -----------------------------------------------------
-- Table `projectx`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`client` (
  `idClient` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `mail` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB
AUTO_INCREMENT = 80
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectx`.`physicalresource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`physicalresource` (
  `idPhysicalResource` INT(11) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `quantity` INT(11) NOT NULL,
  PRIMARY KEY (`idPhysicalResource`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectx`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`user` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `hashpw` VARCHAR(64) NOT NULL,
  `fullname` VARCHAR(45) NULL DEFAULT NULL,
  `type` ENUM('ProjectManager', 'Senior', 'Junior') NOT NULL,
  `salt` VARCHAR(64) NOT NULL,
  `skills` VARCHAR(300) NULL DEFAULT NULL,
  `mail` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectx`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`project` (
  `idProject` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `budget` DOUBLE NULL DEFAULT NULL,
  `idProjectManager` INT(11) NOT NULL,
  `idClient` INT(11) NOT NULL,
  `goals` LONGTEXT NULL DEFAULT NULL,
  `requirements` LONGTEXT NULL DEFAULT NULL,
  `subjectAreas` VARCHAR(300) NULL DEFAULT NULL,
  `deadline` DATE NULL DEFAULT NULL,
  `start` DATE NULL DEFAULT NULL,
  `rateWorkCompleted` FLOAT NULL DEFAULT '0',
  `estimatedCosts` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idProject`),
  INDEX `UserProject_idx` (`idProjectManager` ASC),
  INDEX `ClientProject_idx` (`idClient` ASC),
  CONSTRAINT `ClientProject`
    FOREIGN KEY (`idClient`)
    REFERENCES `projectx`.`client` (`idClient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ProjectManagerProject`
    FOREIGN KEY (`idProjectManager`)
    REFERENCES `projectx`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 81
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectx`.`physicalresourceuse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`physicalresourceuse` (
  `idProject` INT(11) NOT NULL,
  `idPhysicalResource` INT(11) NOT NULL,
  `quantityUsed` INT(11) NOT NULL,
  PRIMARY KEY (`idProject`, `idPhysicalResource`),
  INDEX `ProjectPhysicalResourceUse_idx` (`idProject` ASC),
  INDEX `PhysicalResourceUsed_idx` (`idPhysicalResource` ASC),
  CONSTRAINT `projectResource`
    FOREIGN KEY (`idProject`)
    REFERENCES `projectx`.`project` (`idProject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `resourceUsed`
    FOREIGN KEY (`idPhysicalResource`)
    REFERENCES `projectx`.`physicalresource` (`idPhysicalResource`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectx`.`stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`stage` (
  `idStage` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `startDay` DATE NULL DEFAULT NULL,
  `finishDay` DATE NULL DEFAULT NULL,
  `idSupervisor` INT(11) NULL DEFAULT NULL,
  `idProject` INT(11) NOT NULL,
  `goals` LONGTEXT NULL DEFAULT NULL,
  `requirements` LONGTEXT NULL DEFAULT NULL,
  `outsourcing` ENUM('False', 'True') NULL DEFAULT NULL,
  `rateWorkCompleted` FLOAT NULL DEFAULT '0',
  `relativeWeight` FLOAT NULL DEFAULT '0',
  `critical` ENUM('True', 'False') NULL DEFAULT 'False',
  `status` ENUM('Started', 'Delay', 'CriticalDelay', 'NotStarted') NULL DEFAULT 'NotStarted',
  PRIMARY KEY (`idStage`),
  INDEX `fk_Stage_Project_idx` (`idProject` ASC),
  INDEX `SupervisorStage_idx` (`idSupervisor` ASC),
  CONSTRAINT `ProjectStage`
    FOREIGN KEY (`idProject`)
    REFERENCES `projectx`.`project` (`idProject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SupervisorStage`
    FOREIGN KEY (`idSupervisor`)
    REFERENCES `projectx`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectx`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`task` (
  `idTask` INT(11) NOT NULL AUTO_INCREMENT,
  `startDay` DATE NULL DEFAULT NULL,
  `finishDay` DATE NULL DEFAULT NULL,
  `idStage` INT(11) NOT NULL,
  `completed` ENUM('False', 'True') NULL DEFAULT 'False',
  `name` VARCHAR(150) NULL DEFAULT NULL,
  `relativeWeight` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idTask`),
  INDEX `fk_Task_Stage1_idx` (`idStage` ASC),
  CONSTRAINT `StageTask`
    FOREIGN KEY (`idStage`)
    REFERENCES `projectx`.`stage` (`idStage`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projectx`.`taskdevelopment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`taskdevelopment` (
  `idDeveloper` INT(11) NOT NULL,
  `idTask` INT(11) NOT NULL,
  `workCompleted` ENUM('False', 'True') NULL DEFAULT 'False',
  `hoursRequired` INT(11) NOT NULL,
  PRIMARY KEY (`idDeveloper`, `idTask`),
  INDEX `TaskDeveloped_idx` (`idTask` ASC),
  CONSTRAINT `DeveloperTask`
    FOREIGN KEY (`idDeveloper`)
    REFERENCES `projectx`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `TaskDevelop`
    FOREIGN KEY (`idTask`)
    REFERENCES `projectx`.`task` (`idTask`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
