-- MySQL Script generated by MySQL Workbench
-- mar 16 feb 2016 11:17:06 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projectx
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projectx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectx` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `projectx` ;

-- -----------------------------------------------------
-- Table `projectx`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `hash` VARCHAR(64) NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `type` ENUM('ProjectManager','Senior','Junior') NOT NULL,
  `salt` VARCHAR(64) NOT NULL,
  `skills` VARCHAR(300) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectx`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectx`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`Project` (
  `idProject` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `budget` DOUBLE NULL,
  `idProjectManager` INT NOT NULL,
  `idClient` INT NOT NULL,
  `goals` LONGTEXT NULL,
  `requirements` LONGTEXT NULL,
  `subjectAreas` VARCHAR(300) NULL,
  `estimatedCosts` DOUBLE NULL,
  `deadline` DATE NULL,
  `estimatedDuration` INT NULL,
  PRIMARY KEY (`idProject`),
  INDEX `UserProject_idx` (`idProjectManager` ASC),
  INDEX `ClientProject_idx` (`idClient` ASC),
  CONSTRAINT `ProjectManagerProject`
    FOREIGN KEY (`idProjectManager`)
    REFERENCES `projectx`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ClientProject`
    FOREIGN KEY (`idClient`)
    REFERENCES `projectx`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectx`.`Stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`Stage` (
  `idStage` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `duration` INT NULL,
  `startDay` DATE NULL,
  `finishDay` DATE NULL,
  `idSupervisor` INT NOT NULL,
  `idProject` INT NOT NULL,
  `goals` LONGTEXT NULL,
  `requirements` LONGTEXT NULL,
  PRIMARY KEY (`idStage`),
  INDEX `fk_Stage_Project_idx` (`idProject` ASC),
  INDEX `SupervisorStage_idx` (`idSupervisor` ASC),
  CONSTRAINT `ProjectStage`
    FOREIGN KEY (`idProject`)
    REFERENCES `projectx`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SupervisorStage`
    FOREIGN KEY (`idSupervisor`)
    REFERENCES `projectx`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectx`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`Task` (
  `idTask` INT NOT NULL AUTO_INCREMENT,
  `startDay` DATE NULL,
  `finishDay` DATE NULL,
  `idStage` INT NOT NULL,
  `completed` TINYINT(1) NULL,
  PRIMARY KEY (`idTask`),
  INDEX `fk_Task_Stage1_idx` (`idStage` ASC),
  CONSTRAINT `StageTask`
    FOREIGN KEY (`idStage`)
    REFERENCES `projectx`.`Stage` (`idStage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectx`.`TaskDevelopment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`TaskDevelopment` (
  `idDeveloper` INT NOT NULL,
  `idTask` INT NOT NULL,
  `workCompleted` TINYINT(1) NULL,
  PRIMARY KEY (`idDeveloper`, `idTask`),
  INDEX `TaskDeveloped_idx` (`idTask` ASC),
  CONSTRAINT `TaskDevelop`
    FOREIGN KEY (`idTask`)
    REFERENCES `projectx`.`Task` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DeveloperTask`
    FOREIGN KEY (`idDeveloper`)
    REFERENCES `projectx`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
