-- MySQL Script generated by MySQL Workbench
-- dom 14 feb 2016 16:20:02 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projectx
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projectx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectx` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `projectx` ;

-- -----------------------------------------------------
-- Table `projectx`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`Project` (
  `idProject` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `budget` DOUBLE NULL,
  `projectManager` INT NULL,
  PRIMARY KEY (`idProject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectx`.`Stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`Stage` (
  `idStage` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `duration` INT NULL,
  `startDay` DATE NULL,
  `finishDay` DATE NULL,
  `supervisor` INT NULL,
  PRIMARY KEY (`idStage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectx`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`Task` (
  `idTask` INT NOT NULL AUTO_INCREMENT,
  `startDay` DATE NULL,
  `finishDay` DATE NULL,
  PRIMARY KEY (`idTask`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectx`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectx`.`User` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `hash` VARCHAR(64) NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `type` ENUM('ProjectManager','Senior','Junior') NULL,
  `salt` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
